// Mocks generated by Mockito 5.0.15 from annotations
// in lil_rap_app/test/features/artist_list/data/repositories/rapper_repo_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:lil_rap_app/core/network/network_info.dart' as _i6;
import 'package:lil_rap_app/features/artist_list/data/models/rapper_model.dart'
    as _i4;
import 'package:lil_rap_app/features/artist_list/data/sources/rapper_local_source.dart'
    as _i5;
import 'package:lil_rap_app/features/artist_list/data/sources/rapper_remote_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [RapperRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRapperRemoteSource extends _i1.Mock
    implements _i2.RapperRemoteSource {
  MockRapperRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RapperModel>> getConcreteRapperList() =>
      (super.noSuchMethod(Invocation.method(#getConcreteRapperList, []),
              returnValue:
                  Future<List<_i4.RapperModel>>.value(<_i4.RapperModel>[]))
          as _i3.Future<List<_i4.RapperModel>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RapperLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRapperLocalSource extends _i1.Mock implements _i5.RapperLocalSource {
  MockRapperLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RapperModel>> getLastRapperList() => (super.noSuchMethod(
          Invocation.method(#getLastRapperList, []),
          returnValue: Future<List<_i4.RapperModel>>.value(<_i4.RapperModel>[]))
      as _i3.Future<List<_i4.RapperModel>>);
  @override
  _i3.Future<void> cacheRapperList(List<_i4.RapperModel>? rapperList) =>
      (super.noSuchMethod(Invocation.method(#cacheRapperList, [rapperList]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  String toString() => super.toString();
}
